spring.application.name=spring-security

server.port=8080
server.servlet.context-path=/security

spring.security.user.name=user
spring.security.user.password=user

logging.level.root=INFO
#logging.level.com.example.spring_security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.file.name=logs/security/security.log
#logging.file.path=logs/security/security.log

